name: Common Steps

on:
  workflow_call:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install mdBook
      run: |
        mkdir -p ~/.local/bin
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Linting Markdown Files
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: '**/*.md'

    - name: Preprocess
      run: |
        chmod +x ./scripts/*.sh
        bash ./scripts/update_agents.sh
        bash ./scripts/update_meta.sh
        bash ./scripts/build_date.sh

    - name: MdBook Test
      run: |
        mdbook test

    - name: Install mdbook-linkcheck
      run: |
        mkdir -p mdbook-linkcheck
        cd mdbook-linkcheck
        curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.7/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip
        unzip mdbook-linkcheck.zip
        chmod +x mdbook-linkcheck
        mkdir -p ~/.local/bin
        mv mdbook-linkcheck ~/.local/bin/mdbook-linkcheck
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build
      run: mdbook build

    - name: Store Book Artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: book/html